# Generated by Django 5.2.1 on 2025-05-14 09:59

import debts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма долга')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Остаток долга')),
                ('due_date', models.DateField(default=debts.models.default_due_date, verbose_name='Срок оплаты')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='clients.client', verbose_name='Клиент')),
            ],
        ),
    ]
